name = "JEMSSWrapper"
uuid = "3ffb80e5-d622-48f0-97e0-c485a3b5e49b"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JEMSS = "da3c27b9-5cdd-52db-94a3-a4eefd7acbab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.8"
