[metadata]
name = "auckland_base"
scenario_name = "auckland"
description = "Auckland scenario with standard configuration"
version = "1.0"
author = "JEMSSWrapper"
data_dir = "deps/JEMSS/data/cities/auckland/models/1" # relative to WRAPPER_PATH

[files]
hospitals = "hospitals/hospitals_1.csv"
stations = "stations/stations_1.csv"
nodes = "travel/roads/nodes.csv"
arcs = "travel/roads/arcs.csv"
r_net_travels = "travel/roads/r_net_travels_jl-v1.10.8.jls"
map = "maps/map_1.csv"
travel = "travel/travel/travel_1.csv"
priorities = "misc/call priorities/priorities_1.csv"
stats = "calls/single/train/stats_control.csv"
